FROM nginx:alpine

# Copy nginx configuration
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Increase Nginx's buffer size to handle larger uploads
RUN echo "client_max_body_size 1000M;" > /etc/nginx/conf.d/upload.conf

# Set proper permissions 
RUN chmod -R 755 /usr/share/nginx/html && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d

# Expose port 80
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"] 