version: "3"

services:
  frontend:
    build:
      context: ./nginx
    ports:
      - "$5293:80"
    depends_on:
      - whisper-api
    networks:
      - whisper-network

  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_KEY=${API_KEY:-your-super-secret-api-key}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_PARALLEL_CHUNKS=${MAX_PARALLEL_CHUNKS:-16}
    restart: unless-stopped
    networks:
      - whisper-network

# Define a bridge network to allow internal communication
networks:
  whisper-network:
    driver: bridge
