version: "3.8"

services:
  whisper-transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
    # Remove direct port mapping so it's not exposed to host
    # ports:
    #   - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-your-super-secret-api-key}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_PARALLEL_CHUNKS=${MAX_PARALLEL_CHUNKS:-16}
    restart: unless-stopped
    networks:
      - whisper-network
    # Add container name for easier referencing in client
    container_name: whisper-api

  client:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8362:80"
    depends_on:
      - whisper-transcription-service
    networks:
      - whisper-network
    container_name: whisper-client

# Define a bridge network to allow internal communication
networks:
  whisper-network:
    driver: bridge
